#+include:  ./header.org
#+startup: latexpreview


* Tarefa A
O objetivo dessa tarefa é implementar o método de Euler e o método de Euler-Cromer para
discretização do sistema do pêndulo simples. Primeiramente vamos analisar as equações diferenciais que descrevem
o sistema.

A força atuando no sistema pode ser escrita como \( m a_{\theta } = m l \frac{d^2 }{dt²} \theta  = -g m
\sin \theta   \) e podemos
aproximar o seno fazendo uma expansão de Taylor, temos então 
\[ \sin \theta = \sum_{n = 0}^{\infty} (-1)^n  \frac{\theta ^  {2n+1}}{(2n+1)!} = \theta - \frac{1}{3!}\theta ^3 +
\frac{1}{5!}\theta ^5 + \cdots  \]
para \( \theta  \to 0 \Rightarrow  \sin \theta  \approx \theta  \), segue que
#+begin_latex
\begin{equation}
\frac{d^2}{dt²} \theta  \approx - \frac{g}{l} \theta 
\label{eq:edo1}
\end{equation}
#+end_latex

a (\ref{eq:edo1}) é uma EDO linear e pode ser representada por um sistema de equação diferenciais
acopladas

#+begin_latex
\begin{equation}
\frac{d^2}{dt^2} \theta  = \begin{cases}
    \omega = \frac{d}{dt} \theta  \\
   \frac{d}{dt} \omega = - \frac{g}{l} \theta   
\end{cases}
\end{equation}
\label{eq:edo2}
#+end_latex

discretizando as (\ref{eq:edo2}) temos o método de Euler

#+begin_latex
\begin{equation}
\omega_{i + 1} = \omega_i  - \left( \frac{g}{l} \right) \theta _i \Delta t 
\label{eq:omegaEuler}
\end{equation}
\begin{equation}
\theta _{i + 1} = \theta _i + \omega_i \Delta t
\label{eq:thetaEuler}
\end{equation}
#+end_latex

o método de Euler-Cromer é uma variação do anterior, é representado pelas equações abaixo

#+begin_latex
\begin{equation}
\omega_{i + 1} = \omega_i - \left( \frac{g}{l} \right) \theta _i \Delta t
\label{eq:omegaEulerCromer}
\end{equation}
\begin{equation}
\theta _{i + 1} = \theta _i + \omega_i \Delta t
\label{eq:thetaEulerCromer}
\end{equation}
#+end_latex
#+latex: \clearpage
** Código em Fortran

#+caption: Declaração das variáveis utilizadas. 
#+begin_src fortran :exports code
          implicit real * 8 (a-h, o-z)

          parameter(n = 1000)
          parameter(tt = 50)
          parameter(pi = acos(-1.0d0))

!         Gravidade
          parameter(p = 9.8d0)
!         Comprimento
          parameter(s = 9.8d0)
          dt = (tt * 1.0d0) / (n * 1.0d0)

          tt1 = (2 * pi) / 48d0
          omg1 = 0.0d0
          e1 = (1.0d0/2.0d0)*s**2

          tt2 = tt1 
          omg2 = omg1
          e2 = e1

          open(10, file="data-oscilacoes.dat")
          open(11, file="data-energias.dat")

#+end_src

#+caption: Estrutura dos cálculos e impressão nos arquivos =saida-oscilacoes.dat= e =saida-energias.dat=
#+begin_src fortran :exports code
        do i = 1, n

           t = t + dt

  !     Metodo de Euler
           tmp_omg1 = omg1 - tt1 * dt
           tmp_tt1 = tt1 + omg1 * dt

           omg1 = tmp_omg1
           tt1 = tmp_tt1

  !     Metodo de Euler-Cromer
           tmp_omg2 = omg2 - tt2 * dt
           tmp_tt2 = tt2 + tmp_omg2 * dt
         
           omg2 = tmp_omg2
           tt2 = tmp_tt2

  !     Energia do sistema
           e1 = e1 + (1.0d0/2.0d0) * s ** 3 * (omg1**2 + tt1**2)
           e2 = e2 + (1.0d0/2.0d0) * s ** 3 * (omg2**2 + tt2**2)

           write(10, *) t, omg1, tmp_tt1, omg2, tmp_tt2
           write(11, *) t, e1, e2
        end do
        close(10)
        close(11)
        end
#+end_src
#+latex:\clearpage
** Resultados
Apesar do sistema ser oscilatório e sem presença forças dissipativas, o método de Euler apresenta um
comportamento contrário ao esperado. A amplitude das oscilações aumenta com o tempo. O método pode
não apresentar esse comportamento se a escala de tempo utilizada for muito curta, mas para periodo
maiores de tempo fica aparente.

#+name: grafico-oscilacoes
#+caption: Valores de $\theta$ pelo tempo \( t \) usando método de Euler e o método de Euler-Cromer.
#+attr_latex: :width 15cm :height 10cm :placement [!ht]
[[./tarefa-a/tarefa-a-grafico-oscilacoes.pdf]]


Para entender essa instabilidade do método podemos ánalisar o comportamento da energia mecânica do
sistema. 
\[ E = \Delta K + \Delta U \]
\[ E = \frac{1}{2} m v^2  + mg \Delta h \]
Fazemos \( v = \omega l \)  e como \( \Delta U = mg(h_0 - h)\), onde \( h_0 \) é a posição mais baixa da trajetória, ou seja, a posição onde a
altura onde \( h_0 = l \) e \( h = l \cos \theta   \), então \( \Delta U = mgl(1 - \cos \theta ) \). Segue que

#+begin_latex
\begin{equation}
 E = \frac{1}{2} m\omega^2 l^2  + mgl (1 - \cos \theta ) 
\label{eq:energiaSistema}
\end{equation}
#+end_latex

Note que essa equação cresce pra qualquer valor de \( \theta  \) conforme \( t \) aumenta,
essa é a fonte da instabilidade do método de Euler. Ao contrário do método de
Euler-Cromer, que consegue conservar energia sob periodos inteiros de oscilação, ele
aumenta a energia do mais rapidamente e uma consequência disso é o aumento da amplitude
da oscilação a cada iteração, como está claro no gráfico ([[grafico-oscilacoes]]).


#+name: grafico-energias
#+caption: Energia do sistema calculada pelo método de Euler e Euler-Cromer.
#+attr_latex: :width 12cm :height 10cm :placement [!ht]
[[./tarefa-a/tarefa-a-grafico-energias.pdf]]


#+latex:\clearpage

Para melhor destacar esse comportamento da energia em ambos casos, foi feito o gráfico
abaixo da energia cálculada para cada método em cada iteração.

Essa diferença de precisão entre os dois métodos fica ainda mais visivel para \( t \) muito grande,
abaixo segue um gráfico mostrando o comportamento da oscilação e das energias para \( t = 500 (s) \)
e \( n = 10^4  \) iterações.

#+name: grafico-energias-oscilacoes
#+caption: Gráficos com oscilações e energias usando os dois métodos para \( t =  10^4 \) e \( n = 10^4 \) .
#+attr_latex: :width 12cm :height 17cm :placement [!h]
[[./tarefa-a/tarefa-a-grafico-energias-oscilacao.pdf]]

Por fim, o método de Euler não é um método bom para problemas desse tipo, onde queremos analisar
o comportamento oscilatório para períodos muito longos de tempo. No entanto pode ser útil para
problemas em outras escalas. 


* Tarefa B
Adapte o programa realizado na tarefa A para o caso abaixo, usando o
algorı́tmo de Euler-Cromer.
\[ \frac{d}{dt}\omega = - \frac{g}{l} \sin \theta  - \gamma \frac{d}{dt}\theta  + F_0 \sin \left( \Omega t \right),
\frac{d}{dt} \theta  = \omega \]


* Tarefa C
* Tarefa D
* Tarefa E
#+latex: \clearpage
#+latex: \appendix
#+latex:\pagenumbering{roman}
#+latex:\appendix
* Demonstração da integral eliptíca

Sabemos que a energia do sistema do pêndulo é dada pela fórmula
\(  E = \frac{1}{2} m l^2 \dot{\theta}^2 - mgl \cos \theta  \) e a energia inicial do sistema é \( E = - mg l
\cos \theta _0  \), fazendo
\[ -mgl \cos \theta_0 = \frac{1}{2} m l^2 \dot{\theta}^2 - mgl \cos \theta     \]
multiplicando a equação por \( (1/m) \) temos
\[ -gl \cos \theta _0 = \frac{1}{2} l^2 \dot{\theta}^2 - gl \cos \theta     \]
como queremos chegar numa relação que nos permite escrever o período em função
do angulo \( \theta _0 \), então vamos isolar a derivada da equação, então

\[ gl (\cos \theta - \cos \theta _0) = \frac{1}{2} l^2 \dot{\theta}^2   \]
\[ \frac{2g}{l} \left( \cos \theta -\cos \theta _0    \right)  = \dot{\theta }^2\]

\[ \dot{\theta } = \sqrt{\frac{2g}{l}} \sqrt{\cos \theta - \cos \theta _0}  = \frac{d \theta }{dt} \]

\[ dt = \frac{d \theta }{  \sqrt{\frac{2g}{l}} \sqrt{\cos \theta - \cos \theta _0  }} = \sqrt{\frac{l}{2g}}
\frac{1}{\sqrt{\cos \theta - \cos \theta _0}} d \theta  \]

integrando ambos lados no intervalo \( [ 0, T/2] \), ou seja \( [- \theta _0, \theta _0] \) , temos


\[ \int_{0}^{T/2} dt = \sqrt{ \frac{l}{2g} } \int_{- \theta _0}^{\theta _0} \frac{1}{ \sqrt{\cos \theta - \cos \theta
_0}} d \theta    \]

\[ \frac{T}{2} = \sqrt{\frac{l}{2g}} \int_{- \theta _0}^{\theta _0} \frac{1}{ \sqrt{\cos \theta - \cos \theta
_0}} d \theta   \]

\[ T = 2 \sqrt{\frac{l}{2g}} \int_{- \theta _0}^{\theta _0} \frac{1}{ \sqrt{\cos \theta - \cos \theta
_0}} d \theta = \sqrt{\frac{4l}{2g}} \int_{- \theta _0}^{\theta _0} \frac{1}{ \sqrt{\cos \theta - \cos \theta
_0}} d \theta  \]

#+begin_latex
\begin{equation}
\boxed{ T(\theta _0) = \sqrt{\frac{2l}{g}} \int_{- \theta _0}^{\theta _0} \frac{1}{ \sqrt{\cos \theta - \cos \theta _0}} d \theta  }
\label{eq:integralEliptica}
\end{equation}
#+end_latex



















